<div class="title">
    <h3><?php echo $this->__('Edit Account Information') ?></h3>
</div>

<div class="box-content">
    <form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" autocomplete="off">
        <div class="fieldset account-info">

            <?php echo $this->getBlockHtml('formkey')?>

            <ul class="form-list content-customer-area">
                <li class="clearfix">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
                </li>

                <li class="field clearfix">
                    <label for="email" class="required"><?php echo $this->__('Email Address') . ' *' ?></label>
                    <div class="input-box">
                        <input type="email" name="email" id="email"
                               value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>"
                               title="<?php echo $this->__('Email Address') ?>"
                               class="input-text required-entry validate-email" />
                    </div>
                </li>

                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
                <?php endif ?>
                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
                <?php endif ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                <?php if ($_gender->isEnabled()): ?>
                    <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
                <?php endif ?>
                <li class="control clearfix">
                    <label for="hideit" class="hideit">&nbsp;</label>

                    <input
                        class="checkbox"
                        type="checkbox"
                        name="change_password"
                        id="change_password"
                        value="1"
                        onclick="setPasswordForm(this.checked)"
                        title="<?php echo $this->__('Change Password') ?>"
                        <?php if($this->getCustomer()->getChangePassword() == 1): ?>
                        checked="checked"
                        <?php endif ?>
                        class="checkbox" />
                    <label class="checkbox" for="change_password"><?php echo $this->__('Change Password') ?></label>
                </li>
            </ul>
        </div>
        <div class="fieldset" style="display:none;">
            <h4><?php echo $this->__('Change Password') ?></h4>
            <ul class="form-list content-customer-area">
                <li class="field clearfix">
                    <label for="current_password" class="required"><?php echo $this->__('Current Password') ?></label>
                    <div class="input-box">
                        <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                        <input type="text"
                               class="input-text no-display"
                               name="dummy"
                               id="dummy" />
                        <input type="password"
                               title="<?php echo $this->__('Current Password') ?>"
                               class="input-text"
                               name="current_password"
                               id="current_password" />
                    </div>
                </li>
                <li class="field clearfix">
                    <label for="password" class="required"><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password"
                               title="<?php echo $this->__('New Password') ?>"
                               class="input-text validate-password"
                               name="password"
                               id="password" />
                    </div>
                </li>
                <li class="field clearfix">
                    <label for="confirmation" class="required"><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password"
                               title="<?php echo $this->__('Confirm New Password') ?>"
                               class="input-text validate-cpassword"
                               name="confirmation"
                               id="confirmation" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="fieldset">
            <ul class="form-list">
                <li class="field clearfix">
                    <label for="hideit" class="hideit">&nbsp;</label>
                    <div class="buttons-set">
                        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button strong">
                            <i class="icon-angle-right"></i>
                            <span><?php echo $this->__('Save') ?></span>
                        </button>
                    </div>
                </li>
            </ul>
        </div>

    </form>

    <p class="madatory-info">
        <?php echo '* ' . $this->__('This is a required field.') ?>
    </p>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
    setPasswordForm(true);
    <?php endif ?>
    //]]>
</script>