<?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */

$catalogSearchHelper =  $this->helper('catalogsearch');
?>
<script> Mage.baseUrl = "<?= $this->getUrl() ?>"; </script>
<form id="search_mini_form" action="<?= $catalogSearchHelper->getResultUrl() ?>" method="get" autocomplete="off">

    <fieldset>
        <div class="form-search">
            <label for="search"></label>
            <input id="search" type="text" name="<?= $catalogSearchHelper->getQueryParamName() ?>"
                   placeholder="<?= $this->__('What are you looking for?') ?>"
                   class="input-text"
                   autocomplete="off" />

            <button class="search-btn" type="submit" title="<?= $this->__('Search') ?>">
                <svg class="icon magnifier" viewBox="0 0 1024 1024">
                    <use xlink:href="<?= $this->getSkinUrl('images/assets.svg')?>#magnifier"></use>
                </svg>
            </button>

            <div id="search-autosuggestion"></div>
        </div>
    </fieldset>

</form>
