<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>

<div class="col span_6 login">

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <div class="title">
            <h2><?php echo $this->__('Login, if you already have an account at Craft') ?></h2>
        </div>

        <?php echo $this->getBlockHtml('formkey') ?>

        <div class="content">
            <ul class="form-list">
                <li class="clearfix">
                    <label for="email" class="required"><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="email" name="login[username]"
                               value="<?php echo $this->escapeHtml($this->getUsername()) ?>"
                               id="email" class="input-text required-entry validate-email"
                               title="<?php echo $this->__('Email Address') ?>" />
                    </div>
                </li>
                <li class="clearfix">
                    <label for="pass" class="required"><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" name="login[password]" class="input-text required-entry validate-password"
                               id="pass" title="<?php echo $this->__('Password') ?>" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info') ?>
                <li class="clearfix">
                    <label for="hideit" class="hideit">&nbsp;</label>
                    <div class="button-set clearfix">
                        <button type="submit" class="button strong" title="<?php echo $this->__('Login') ?>" name="send" id="send2">
                            <i class="icon-angle-right"></i>
                            <span><?php echo $this->__('Login') ?></span>
                        </button>
                        <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="forgot-password">
                            <?php echo $this->__('Forgot Your Password?') ?>
                        </a>
                    </div>
                </li>
            </ul>

        </div>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif ?>

    </form>

    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //]]>
    </script>

    <?php // Display the shop advantages ?>
    <div class="trust-element">
        <?php
        echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout_trust_block')->toHTML();
        ?>
    </div>
</div>
