<?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button"
            title="<?php echo $this->__('Checkout') ?>"
            class="button strong cart<?php if ($this->isDisabled()):?> no-checkout<?php endif ?>"
        <?php if ($this->isDisabled()):?>
            disabled="disabled"
        <?php endif ?>
            onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
        <?php echo $this->__('Checkout') ?>
    </button>
<?php endif?>
