<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php if($this->getCollection()->getSize()): ?>

    <?php if($this->getLastPageNum() > 1): ?>
        <ul class="pages">
            <?php if (!$this->isFirstPage()): ?>
                <li>
                    <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif ?>"
                       href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                        <i class="icon-left"></i>
                    </a>
                </li>
            <?php endif ?>

            <?php if ($this->canShowFirst()): ?>
                <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
            <?php endif ?>

            <?php if ($this->canShowPreviousJump()): ?>
                <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">&hellip;</a></li>
            <?php endif ?>

            <?php foreach ($this->getFramePages() as $_page): ?>
                <?php if ($this->isPageCurrent($_page)): ?>
                    <li class="current"><?php echo $_page ?></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                <?php endif ?>
            <?php endforeach ?>


            <?php if ($this->canShowNextJump()): ?>
                <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>"></a></li>
            <?php endif ?>

            <?php if ($this->canShowLast()): ?>
                <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
            <?php endif ?>

            <?php if (!$this->isLastPage()): ?>
                <li>
                    <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif ?>"
                       href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>">
                        <i class="icon-right"></i>
                    </a>
                </li>
            <?php endif ?>
        </ul>
    <?php endif ?>

<?php endif ?>
