<?php
/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?= $this->getChildOutput('title') ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<link rel="icon" href="<?= $this->getBaseUrl() ?>images/favicon.ico" type="image/x-icon" />

<link type="text/css" rel="stylesheet" href="<?= $this->getBaseUrl() ?>css/<?= $this->getLayoutHandle() ?>.css" />

<script data-main="<?= $this->getBaseUrl() ?>js/<?= $this->getLayoutHandle() ?>" src="<?= $this->getBaseUrl() ?>js/lib/require.js"></script>
{{snippet head_container}}
