<?php

declare(strict_types=1);

/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */
?>
<?= $this->getChildOutput('product_listing_content_block_top') ?>
<script>
    var productListingJson = {{snippet product_grid}},
        totalNumberOfResults = {{snippet total_number_of_results}},
        productsPerPage = {{snippet products_per_page}},
        availableSortOrders = {{snippet available_sort_orders}},
        selectedSortOrder = {{snippet selected_sort_order}},
        translations = {{snippet translations}},
        baseUrl = '<?= $this->getBaseUrl() ?>',
        assetsBaseUrl = '<?= $this->getAssetsBaseUrl() ?>',
        basePricePattern = '<?= sprintf($this->__('per %s%s %s &euro;'), '%s', '%s', '%s') ?>';
</script>
