<?php
/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */
?>
<?= $this->getChildOutput('product_listing_content_block_top') ?>
<script>
    var productListingJson = {{snippet product_grid}},
        totalNumberOfResults = {{snippet total_number_of_results}},
        productsPerPage = {{snippet products_per_page}},
        sortOrderConfig = {{snippet sort_order_config}},
        translations = {{snippet translations}},
        baseUrl = '<?= $this->getBaseUrl() ?>',
        basePricePattern = '<?= sprintf($this->__('per %s%s %s &euro;'), '%s', '%s', '%s') ?>';
</script>
