<?php
/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */
?>
<ul>
    <li class="no-thumbnail">
        <a href="<?= $this->getBaseUrl() ?>catalogsearch/result?q={{snippet query_string}}">
            {{snippet query_string}} ({{snippet total_number_of_results}} <?= $this->__('results') ?>)
        </a>
    </li>
    {{snippet product_1}}
    {{snippet product_2}}
    {{snippet product_3}}
    {{snippet product_4}}
    {{snippet product_5}}
    <li class="no-thumbnail">
        <a href="<?= $this->getBaseUrl() ?>catalogsearch/result?q={{snippet query_string}}"><?= $this->__('More search results') ?></a>
    </li>
</ul>
