<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<?php
$cart = Mage::helper('checkout/cart');
$items = $cart->getItemsCount();
$total = $cart->getQuote()->getGrandTotal();
$storeCode = Mage::app()->getStore()->getCode();
$customerSession = Mage::getSingleton('customer/session');
$currentCat = null;

if (Mage::registry('current_category')) {
    $currentCat = Mage::registry('current_category')->getName() . ' - ';
}
?>
<header>
    <div class="language-wrapper">
        <?php echo $this->getChildHtml('store_language') ?>
    </div>

    <?php echo $this->getChildHtml('mothership.ipswitch') ?>

    <div class="header-wrapper clearfix">

        <div id="mobile-menu">
            <span class="lines"></span>
        </div>

        <a href="<?php echo $this->getUrl('') ?>"
           title="<?php echo $currentCat . $this->__(' - Lizards & Pumpkins') ?>"
           class="logo" >
            <svg class="icon main-logo" viewBox="0 0 1024 1024">
                <use xlink:href="<?php echo $this->getSkinUrl('images/assets.svg')?>#main-logo"></use>
            </svg>
            <svg class="icon mobile-logo" viewBox="0 0 1024 1024">
                <use xlink:href="<?php echo $this->getSkinUrl('images/assets.svg')?>#mobile-logo"></use>
            </svg>
        </a>

        <i id="mobile-search">
            <svg class="icon magnifier" viewBox="0 0 1024 1024">
                <use xlink:href="<?php echo $this->getSkinUrl('images/assets.svg')?>#magnifier"></use>
            </svg>
        </i>

        <ul class="top-links">
            <li class="login">
            <?php if (!$customerSession->isLoggedIn()): ?>
                <a href="<?php echo $this->getUrl('customer/account/login') ?>" class="customer-account">
                    <span><?php echo $this->__('Login / Register') ?></span>
                </a>

            <?php else: ?>

                <?php $customerName = $customerSession->getCustomer()->getFirstname() ?>
                <a href="<?php echo $this->getUrl('customer/account') ?>" class="customer-account">
                    <span><?php echo $this->__('Hi, %s', $customerName) ?></span>
                </a>
                <a href="<?php echo $this->getUrl('customer/account/logout') ?>">
                    <?php echo $this->__('Log out') ?>
                </a>
            <?php endif ?>
            </li>
            <li id="language-switcher" class="store-code">
                <img src="<?php echo $this->getSkinUrl('images/flags/') . $storeCode . '.png'?>" alt="<?php echo $storeCode ?>">
            </li>
            <li class="cart"><?php echo $this->getChildHtml('miniCart') ?></li>
        </ul>

        <?php echo $this->getChildHtml('topSearch') ?>
    </div>

    <div class="nav-wrapper clearfix">
        <?php echo $this->getChildHtml('main.menu') ?>
    </div>
</header>