<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->canApplyMsrp()): ?>
    <div class="cart-msrp-totals"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER') ?></div>
<?php else: ?>
    <div id="shopping-cart-totals-table">
        <?php echo $this->renderTotals() ?>
        <?php echo $this->renderTotals('footer') ?>
    </div>
<?php endif ?>