<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
    <div id="zoom-image" data-zoom="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(1000) ?>">
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(520) ?>"
             alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
             title="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
             id="image" />
    </div>
<?php endif ?>

<?php if (count($this->getGalleryImages()) > 1): ?>
    <div class="more-views">
        <ul>
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <li>
                    <div data-src="<?php echo $this->helper('catalog/image')
                                                   ->init($this->getProduct(), 'image', $_image->getFile())
                                                   ->resize(520) ?>"
                         data-zoom="<?php echo $this->helper('catalog/image')
                                                   ->init($this->getProduct(), 'image', $_image->getFile())
                                                   ->resize(1000) ?>"
                         class="gallery-image"
                         title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
                        <img src="<?php echo $this->helper('catalog/image')
                                                  ->init($this->getProduct(), 'thumbnail', $_image->getFile())
                                                  ->resize(56) ?>"
                             width="56"
                             height="56"
                             alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
<?php endif ?>

<div id="product-image-popup">
    <i class="popup-close"></i>
    <div class="image">
        <img data-src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(1000) ?>"
             alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
             id="popup-image"/>
    </div>
</div>
