<?php $_orders = $this->getOrders() ?>
<div class="title">
    <h3><?php echo $this->__('My Orders') ?></h3>
</div>

<div class="box-content">
    <div class="pager">
        <?php echo $this->getPagerHtml() ?>
    </div>

    <?php if($_orders->getSize()): ?>
        <table class="data-table history" id="my-orders-table">
            <col width="1" />
            <col width="1" />
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />

            <thead>
                <th><?php echo $this->__('Order Nr.') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <th><?php echo $this->__('Total') ?></th>
                <th><?php echo $this->__('Status') ?></th>
                <th>&nbsp;</th>
            </thead>

            <tbody>
            <?php $_odd = '' ?>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td><?php echo $_order->getRealOrderId() ?></td>
                    <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td class="<?php echo $_order->getStatus() ?>"><?php echo $_order->getStatusLabel() ?></td>
                    <td>
                        <a href="<?php echo $this->getViewUrl($_order) ?>">
                            <?php echo $this->__('View Order') ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('my-orders-table');</script>

    <div class="pager">
        <?php echo $this->getPagerHtml() ?>
    </div>

    <?php else: ?>
        <p><?php echo $this->__('You have placed no orders.'); ?></p>
    <?php endif ?>
</div>