<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>

<div class="page-title">
    <h3><?php echo $this->__('Order %s <span>- %s</span> - of %s', $_order->getRealOrderId(), $_order->getStatusLabel(), $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></h3>
</div>


<?php $_links = $this->getLinks() ?>
<ul id="order-info-tabs">
<?php foreach ($_links as $_link): ?>
    <?php if($_link->getUrl()): ?>
        <li>
            <a href="<?php echo $_link->getUrl() ?>">
                <?php echo $_link->getLabel() ?>
            </a>
        </li>
    <?php else: ?>
        <li class="current">
            <?php echo $_link->getLabel() ?>
        </li>
    <?php endif ?>
<?php endforeach ?>
</ul>

<div class="order-buttons">
    <?php echo $this->getChildHtml('buttons') ?>
</div>

<?php if (!$_order->getIsVirtual()): ?>
<div class="box clearfix">
    <div class="col span_6">
        <div class="box">
            <div class="box-title">
                <h4><?php echo $this->__('Shipping Address') ?></h4>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col span_6">
        <div class="box">
            <div class="box-title">
                <h4><?php echo $this->__('Shipping Method') ?></h4>
            </div>
            <div class="box-content">
                <?php if ($_order->getShippingDescription()): ?>
                    <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
                <?php else: ?>
                    <p><?php echo $this->helper('sales')->__('No shipping information available') ?></p>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>
<?php endif ?>

<div class="box clearfix">
    <div class="col span_6">
        <div class="box">
            <div class="box-title">
                <h4><?php echo $this->__('Billing Address') ?></h4>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col span_6">
        <div class="box box-payment">
            <div class="box-title">
                <h4><?php echo $this->__('Payment Method') ?></h4>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
